name: Sync Publish to Release Branch with Timestamped Backup

on:
  workflow_dispatch:
    inputs:
      publish_branch:
        description: 'Source branch to copy files from'
        required: true
        default: 'publish_branch'
      release_branch:
        description: 'Target branch to copy files to'
        required: true
        default: 'release_branch'

jobs:
  sync-files:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.publish_branch }}  # Checkout the specified publish_branch

      - name: Create Backup Directory
        run: mkdir -p BACKUP/${{ github.run_id }}

      - name: Copy Files to Backup with Timestamp
        run: |
          rsync -av --exclude='.git/' mx-core-data-dev-dfws/ BACKUP/${{ github.run_id }}/
        # Use github.run_id for timestamped folder in BACKUP

      - name: Commit and Push Changes
        run: |
          git config --global user.email "adarsh.singh@kroger.com"
          git config --global user.name "adarshs-kr"

          git checkout ${{ github.event.inputs.release_branch }}
          git add BACKUP/
          git commit -m "Backup from ${{ github.event.inputs.publish_branch }} at ${TIMESTAMP}"
          git push origin ${{ github.event.inputs.release_branch }}
