name: Sync Publish to Release Branch with Timestamped Backup

on:
  workflow_dispatch:
    inputs:
      publish_branch:
        description: 'Source branch to copy files from'
        required: true
        default: 'publish_branch'
      release_branch:
        description: 'Target branch to copy files to'
        required: true
        default: 'release_branch'

jobs:
  sync-files:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Publish Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.publish_branch }}

      - name: Create Backup Directory
        run: mkdir -p BACKUP/${{ github.run_id }}

      - name: Copy Files to Backup with Timestamp
        run: |
          rsync -av --exclude='.git/' mx-core-data-dev-dfws/ BACKUP/${{ github.run_id }}/
        # Use github.run_id for timestamped folder in BACKUP

      - name: Checkout Release Branch
        run: |
          git fetch origin ${{ github.event.inputs.release_branch }}:${{ github.event.inputs.release_branch }}
          git checkout ${{ github.event.inputs.release_branch }}

      - name: Add Backup Files
        run: git add BACKUP/

      - name: Commit Changes
        run: |
          git commit -m "Backup from ${{ github.event.inputs.publish_branch }} at ${TIMESTAMP}"

      - name: Push Changes
        run: git push origin ${{ github.event.inputs.release_branch }}
